"""Initial migration

Revision ID: 44255cd87cd0
Revises: 
Create Date: 2025-04-12 19:37:04.039274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44255cd87cd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movietitle', sa.String(length=150), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('poster',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('poster',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('movietitle')

    # ### end Alembic commands ###
