"""Updated movies table schema

Revision ID: b0c645909be3
Revises: 44255cd87cd0
Create Date: 2025-04-13 14:33:02.732351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c645909be3'
down_revision = '44255cd87cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('poster',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_column('movietitle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movietitle', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.alter_column('poster',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
